export const BANK_LIST_LOADING = 'BANK_LIST_LOADING';
export const BANK_LIST_DATA = 'BANK_LIST_DATA';
export const BANK_LIST_STATUS = 'BANK_LIST_STATUS';
export const BANK_LIST_ERROR = 'BANK_LIST_ERROR';

export const PAYMENT_DETAIL_LOADING = 'PAYMENT_DETAIL_LOADING';
export const PAYMENT_DETAIL_DATA = 'PAYMENT_DETAIL_DATA';
export const PAYMENT_DETAIL_STATUS = 'PAYMENT_DETAIL_STATUS';
export const PAYMENT_DETAIL_ERROR = 'PAYMENT_DETAIL_ERROR';
